name = "serverless-discord-bot"
type = "javascript"
zone_id = ""
account_id = "3f5c1e51a6eecd0be8410b949ac69d09"
route = ""
workers_dev = true
compatibility_date = "2022-01-06"

[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"
